name: Build Windows App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          pip install PyQt6 pyinstaller
          
      - name: Compile to .exe
        run: |
          pyinstaller --noconsole --onefile --icon=ie_icon.ico main.py
          
      - name: Save Executable
        uses: actions/upload-artifact@v4
        with:
          name: Internet-Explorative-Windows
          path: dist/main.exe
